name: Deploy to cPanel

on:
  push:
    branches:
      - main  # Adjust this to the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install lftp
      run: sudo apt-get install -y lftp

    - name: Deploy to cPanel using FTPS
      env:
        FTP_SERVER: gold.server24.arhamsoft.dev
        FTP_USERNAME: ${{ secrets.CPANEL_USERNAME }}
        FTP_PASSWORD: ${{ secrets.CPANEL_PASSWORD }}
      run: |
        lftp -u $FTP_USERNAME,$FTP_PASSWORD $FTP_SERVER <<EOF
        set ftp:ssl-allow yes
        set ssl:verify-certificate no
        mirror -R ./ /public_html
        bye
        EOF
