name: Deploy to cPanel

on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to cPanel
      env:
        CPANEL_URL: ${{ secrets.CPANEL_URL }}
        CPANEL_USERNAME: ${{ secrets.CPANEL_USERNAME }}
        CPANEL_PASSWORD: ${{ secrets.CPANEL_PASSWORD }}
      run: |
        # Compress the files to upload
        zip -r website.zip .

        # Upload to cPanel
        curl --insecure -u $CPANEL_USERNAME:$CPANEL_PASSWORD \
          --form "file=@website.zip" \
          "$CPANEL_URL/api/upload?dir=public_html"

        # Optionally, you can add a step to unzip the uploaded file using a cPanel UAPI call

